server:
  port: 8888

spring:
  datasource:
    url: jdbc:h2:/tmp/conductordb;AUTO_SERVER=TRUE
    platform: h2
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: impresario.api.repository.ImpresarioApiPhysicalNamingStrategy
